CreateThread(function()
    AddTextEntry('shinobid', 'Shinobi Drag')
	AddTextEntry('SHINOBID_PLATE0', 'No Plate and Blinkers')
	AddTextEntry('SHINOBID_PLATE', 'Swing Arm Plate')
	AddTextEntry('SHINOBID_CHARM1', 'Glowing Heart Charm')
	AddTextEntry('SHINOBID_CHARM2', 'Grim Reaper Charm')
	AddTextEntry('SHINOBID_CHARM3', 'Black Skull Charm')
	AddTextEntry('SHINOBID_CHARM4', 'Princess Robot Bubble Gum Charm')
	AddTextEntry('SHINOBID_CHARM5', 'Bear Charm')
	AddTextEntry('SHINOBID_CHARM6', 'Jack-O-Lantern')
	AddTextEntry('SHINOBID_CHARM7', 'Sword Charm')
	AddTextEntry('SHINOBID_CHARM8', 'Golden Revolver Charm')
	AddTextEntry('SHINOBID_SWARM1', 'Primary Swing Arm')
	AddTextEntry('SHINOBID_SWARM2', 'Secondary Swing Arm')
	AddTextEntry('SHINOBID_SWARM3', 'Glowing Trim Swing Arm')
	AddTextEntry('SHINOBID_BODY1', 'Primary Body Trim')
	AddTextEntry('SHINOBID_BODY2', 'Secondary Body Trim')
	AddTextEntry('SHINOBID_BODY3', 'Glowing Body Trim')
	AddTextEntry('SHINOBID_EXH1', 'Carbon Exhausts')
	AddTextEntry('SHINOBID_EXH2', 'Aftermarket Exhausts')
	AddTextEntry('SHINOBID_EXH3', 'Single Side Pipe')
	AddTextEntry('SHINOBID_EXH4', 'Short Side Pipes')
	AddTextEntry('SHINOBID_EXH5', 'Titanium Short Pipes')
	AddTextEntry('SHINOBID_EXH6', 'Right Side Exits')
	AddTextEntry('SHINOBID_EXH7', 'Twin Side Exits')
	AddTextEntry('SHINOBID_EXH8', 'Primary Painted Exhausts')
	AddTextEntry('SHINOBID_EXH9', 'Secondary Painted Exhausts')
	AddTextEntry('SHINOBID_EXH10', 'Glowing Paint Exhausts')
	AddTextEntry('SHINOBID_EXH11', 'Quad Exit Exhausts')
	AddTextEntry('SHINOBID_EXH12', 'Quad Exit Exhausts W/ Glowing Trim')
	AddTextEntry('SHINOBID_TURBO1', 'Primary Turbo Mesh')
	AddTextEntry('SHINOBID_TURBO2', 'Secondary Turbo Mesh')
	AddTextEntry('SHINOBID_TURBO3', 'Glowing Turbo Mesh')
	AddTextEntry('SHINOBID_TURBO4', 'Turbo Air Filter')
	AddTextEntry('SHINOBID_TANK1', 'Primary Custom Tanks')
	AddTextEntry('SHINOBID_TANK2', 'Secondary Custom Tanks')
	AddTextEntry('SHINOBID_TANK3', 'Mysterious Glowing Liquid')
	AddTextEntry('SHINOBID_HLIGHTS1', 'Painted Headlights')
	AddTextEntry('SHINOBID_HLIGHTS2', 'LED Headlights')
	AddTextEntry('SHINOBID_HLIGHTS3', 'Painted LED Headlights')
	AddTextEntry('SHINOBID_TLIGHTS1', 'Custom Tail Lights')
	AddTextEntry('SHINOBID_TLIGHTS2', 'LED Tail Lights')
	AddTextEntry('SHINOBID_TLIGHTS3', 'Painted LED Tail Lights')
	AddTextEntry('SHINOBID_WSHIELD1', 'Custom Windscreen')
	AddTextEntry('SHINOBID_WSHIELD2', 'Primary Windscreen')
	AddTextEntry('SHINOBID_WSHIELD3', 'Secondary Windscreen')
	AddTextEntry('SHINOBID_WSHIELD4', 'Primary Solid Windscreen')
	AddTextEntry('SHINOBID_WSHIELD5', 'Secondary Solid Windscreen')
end)