CreateThread(function()
    AddTextEntry('cyclone2c', 'Cyclone V10 Custom')
	AddTextEntry('CYCLONE2C_CHARM1', 'Glowing Heart Charm')
	AddTextEntry('CYCLONE2C_CHARM2', 'Grim Reaper Charm')
	AddTextEntry('CYCLONE2C_CHARM3', 'Black Skull Charm')
	AddTextEntry('CYCLONE2C_CHARM4', 'Princess Robot Bubble Gum Charm')
	AddTextEntry('CYCLONE2C_CHARM5', 'Bear Charm')
	AddTextEntry('CYCLONE2C_CHARM6', 'Jack-O-Lantern')
	AddTextEntry('CYCLONE2C_CHARM7', 'Sword Charm')
	AddTextEntry('CYCLONE2C_CHARM8', 'Golden Revolver Charm')
	AddTextEntry('CYCLONE2C_STWHEEL1', 'Race Steering Wheel')
	AddTextEntry('CYCLONE2C_STWHEEL2', 'Track Steering Wheel')
	AddTextEntry('CYCLONE2C_WB', 'Bolt-On Widebody')
	AddTextEntry('CYCLONE2C_HLIGHT1', 'Painted Headlights')
	AddTextEntry('CYCLONE2C_HLIGHT2', 'X Headlights')
	AddTextEntry('CYCLONE2C_HLIGHT3', 'Painted X Headlights')
	AddTextEntry('CYCLONE2C_HLIGHT4', 'Heart Headlights')
	AddTextEntry('CYCLONE2C_HLIGHT5', 'Painted Heart Headlights')
	AddTextEntry('CYCLONE2C_WING14', 'Primary Lip Spoiler')
	AddTextEntry('CYCLONE2C_WING15', 'Secondary Lip Spoiler')
	AddTextEntry('CYCLONE2C_WING16', 'Carbon Lip Spoiler')
	AddTextEntry('CYCLONE2C_WING17', 'Aggressor Wing')
	AddTextEntry('CYCLONE2C_WING18', 'Fighter Wing')
	AddTextEntry('CYCLONE2C_WING19', 'Track Day Wing')
	AddTextEntry('CYCLONE2C_WING20', 'Concept Wing')
	AddTextEntry('CYCLONE2C_SPLIT1', 'Glowing Trim Spiltter')
	AddTextEntry('CYCLONE2C_DIFF1', 'Glowing Diffuser')
	AddTextEntry('CYCLO2_SKIRT_L', 'Glowing GT Skirt')
	AddTextEntry('CYCLONE2C_EXH1', 'Rectangle Exhaust')
	AddTextEntry('CYCLONE2C_EXH2', 'Expansive Exhaust')
	AddTextEntry('CYCLONE2C_EXH3', 'Quad Exhaust')
	AddTextEntry('CYCLONE2C_EXH4', 'Triple Exit Exhaust')
	AddTextEntry('CYCLONE2C_EXH5', 'Dual Quad Exit Exhaust')
	AddTextEntry('CYCLONE2C_EXH6', 'Angular Triple Exits')
	AddTextEntry('CYCLONE2C_EXH7', 'Quad Exits')
	AddTextEntry('CYCLONE2C_HOOD1', 'Primary Engine Cover')
	AddTextEntry('CYCLONE2C_HOOD2', 'Secondary Engine Cover')
	AddTextEntry('CYCLONE2C_HOOD3', 'Carbon Engine Cover')
	AddTextEntry('CYCLONE2C_HOOD4', 'Primary Scooped Engine Cover')
	AddTextEntry('CYCLONE2C_HOOD5', 'Secondary Scooped Engine Cover')
	AddTextEntry('CYCLONE2C_HOOD6', 'Carbon Scooped Engine Cover')
	AddTextEntry('CYCLO2_FEND0', 'Front Fenders Delete')
end)